general:
  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:

    sequences:

    parallels:
      priority_level_1: [pl_floor_intake, pl_shoot, pl_protect, pl_prime]

    ss_drivetrain:
      default: [st_drivetrain_percent]

    ss_collector:
      priority_level_2: [st_collector_zero]
      priority_level_1: [st_collector_floor_intake, st_collector_extend]
      default: [st_collector_retract]

    ss_hopper:
      priority_level_2: [st_hopper_zero]
      priority_level_1: [st_hopper_home, st_hopper_collect, st_hopper_shoot]
      default: [st_hopper_stop]

    ss_elevator:
      priority_level_2: [st_elevator_zero]
      priority_level_1: [st_elevator_load, st_elevator_prime, st_elevator_shoot]
      default: [st_elevator_stop]


  subsystems: [ss_drivetrain, ss_collector, ss_hopper, ss_elevator]



  input_booleans: [
    ipb_driver_a, ipb_driver_b, ipb_driver_y, ipb_driver_x, ipb_driver_left_bumper, ipb_driver_right_bumper, ipb_driver_left_trigger, ipb_driver_right_trigger, ipb_driver_dpad_up, ipb_driver_dpad_down, ipb_driver_dpad_left, ipb_driver_dpad_right, ipb_driver_back, ipb_driver_start, ipb_driver_left_stick_button, ipb_driver_right_stick_button,
    ipb_operator_a, ipb_operator_b, ipb_operator_y, ipb_operator_x, ipb_operator_left_bumper, ipb_operator_right_bumper, ipb_operator_left_trigger, ipb_operator_right_trigger, ipb_operator_dpad_up, ipb_operator_dpad_down, ipb_operator_dpad_left, ipb_operator_dpad_right, ipb_operator_back, ipb_operator_start, ipb_operator_left_stick_button, ipb_operator_right_stick_button,
    ipb_hopper_home_switch, ipb_elevator_beam_sensor
  ]

  input_numerics: [
    ipn_driver_left_y, ipn_driver_right_x,
  ]

  input_vectors: []

  output_numerics: [opn_drivetrain_right, opn_drivetrain_left, opn_collector_rollers, opn_hopper, opn_elevator]

  output_booleans: [opb_drivetrain_gear_shifter, opb_collector_extend, opb_hopper_kicker]



global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_core_thread: 80
  frame_cycle_time_threshold_info_thread: 80

global_drivetrain:
  x: ipn_driver_right_x
  y: ipn_driver_left_y
  gear_shift_button: ipb_driver_left_trigger

global_collector:
  delay_time: 500

global_hopper:
  kicker_position: opb_hopper_kicker
  hopper_speed: opn_hopper

global_elevator:
  increment_up_button: ipb_operator_y
  increment_down_button: ipb_operator_a
  initial_speed: 0.0
  increment: 0.1



log:

global_webdashboard:

  auto_selector:
    origins: []
    destinations: []
    actions: []

  match_values: